In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt

In [3]:
clinical_data = pd.read_csv('..\\data\\NSCLCR01Radiogenomic_DATA_LABELS_2018-05-22_1500.csv', index_col=False)

In [4]:
# clinical_data = clinical_data.drop(['Case ID','Patient affiliation','%GG', 'Survival Status','Date of Last Known Alive', 'Date of Last Known Alive', 'CT Date', 'PET Date', 'Date of Recurrence'], axis=1)
clinical_data.head(2)

Age at Histological Diagnosis Weight (lbs)  Gender  Ethnicity  \
0                             79          146  Female  Caucasian   
1                             65          195  Female      Asian   

  Smoking status Tumor Location (choice=RUL) Tumor Location (choice=RML)  \
0         Former                     Checked                   Unchecked   
1      Nonsmoker                     Checked                   Unchecked   

  Tumor Location (choice=RLL) Tumor Location (choice=LUL)  \
0                   Unchecked                   Unchecked   
1                   Unchecked                   Unchecked   

  Tumor Location (choice=LLL)  ...  \
0                   Unchecked  ...   
1                   Unchecked  ...   

  Pleural invasion (elastic, visceral, or parietal) EGFR mutation status  \
0                                                No              Unknown   
1                                                No              Unknown   

  KRAS mutation status ALK translocation status Adjuvant Treatment  \
0              Unknown                  Unknown                 No   
1              Unknown                  Unknown                 No   

  Chemotherapy Radiation Recurrence Location Days between CT and surgery  \
0           No        No                 NaN                          42   
1           No        No                 NaN                          23   

  Recurrence  
0         no  
1         no  

[2 rows x 28 columns]

In [6]:
# clinical_data['Quit Smoking Year'] = pd.to_datetime(clinical_data['Quit Smoking Year'], format='%Y')

In [7]:
# clinical_data['Quit Smoking Year']

In [8]:
#replace Not Collected with NaN
clinical_data.replace('Not Collected', 'NaN', inplace=True)
clinical_data.replace('Not collected', 'NaN', inplace=True)
clinical_data.replace('Not Recorded In Database', 'NaN', inplace=True)
clinical_data.replace('NaN', np.nan, inplace=True)

In [9]:
#weight to numerical value
clinical_data['Weight (lbs)'] = pd.to_numeric(clinical_data['Weight (lbs)'])
# clinical_data.astype({'Weight (lbs)':'Int32'})

In [10]:
# clinical_data['Quit Smoking'] = clinical_data['Quit Smoking Year'].isnull()
# clinical_data['Quit Smoking Year'] = clinical_data.drop('Quit Smoking Year', axis=1)

In [11]:
clinical_data['Weight (lbs)'].fillna(-999, inplace=True)

In [12]:
dm = pd.DataFrame(pd.get_dummies(clinical_data))

In [13]:
dm = dm.drop(['Recurrence_no'], axis=1)

In [14]:
clinical_data['Weight (lbs)']

0      146.0
1      195.0
2     -999.0
3     -999.0
4      145.0
       ...  
157    184.0
158    231.5
159   -999.0
160    158.0
161    229.0
Name: Weight (lbs), Length: 162, dtype: float64

In [16]:
# clinical_data['Quit Smoking']

In [17]:
#define x and y
X = dm.iloc[:, dm.columns != 'Recurrence_yes']
y = dm.iloc[:,-1].values

In [20]:
#clinical_data.iloc[:,-1]

Train Test Split

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

In [19]:
X_train

Age at Histological Diagnosis  Weight (lbs)  Days between CT and surgery  \
85                              68       171.990                           14   
55                              71       180.810                            9   
160                             67       158.000                           65   
18                              71       205.000                           42   
92                              83       201.000                           73   
..                             ...           ...                          ...   
9                               72      -999.000                           52   
103                             76       229.000                            2   
67                              63       183.015                           29   
117                             80       201.000                            3   
47                              77       185.220                           63   

     Gender_Female  Gender_Male  Ethnicity_African-American  Ethnicity_Asian  \
85               0            1                           0                0   
55               0            1                           0                0   
160              0            1                           0                1   
18               0            1                           0                0   
92               0            1                           0                0   
..             ...          ...                         ...              ...   
9                0            1                           0                0   
103              0            1                           0                0   
67               0            1                           0                0   
117              0            1                           0                0   
47               0            1                           0                0   

     Ethnicity_Caucasian  Ethnicity_Hispanic/Latino  \
85                     0                          0   
55                     1                          0   
160                    0                          0   
18                     1                          0   
92                     1                          0   
..                   ...                        ...   
9                      1                          0   
103                    1                          0   
67                     1                          0   
117                    1                          0   
47                     1                          0   

     Ethnicity_Native Hawaiian/Pacific Islander  ...  \
85                                            1  ...   
55                                            0  ...   
160                                           0  ...   
18                                            0  ...   
92                                            0  ...   
..                                          ...  ...   
9                                             0  ...   
103                                           0  ...   
67                                            0  ...   
117                                           0  ...   
47                                            0  ...   

     ALK translocation status_Wildtype  Adjuvant Treatment_No  \
85                                   1                      0   
55                                   1                      1   
160                                  1                      1   
18                                   1                      1   
92                                   0                      1   
..                                 ...                    ...   
9                                    1                      1   
103                                  1                      1   
67                                   1                      0   
117                                  1                      0   
47                    

Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
y_train

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0], dtype=uint8)

In [22]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

nb_y_predict = nb_classifier.predict(X_test)
nb_y_predict

from sklearn.metrics import confusion_matrix,accuracy_score,recall_score, precision_score
cm = confusion_matrix(y_test, nb_y_predict)
ac = accuracy_score(y_test,nb_y_predict)
rs = recall_score(y_test,nb_y_predict)
ps = precision_score(y_test,nb_y_predict)

print(cm)
print(ac)
print(rs)
print(ps)

[[38  1]
 [ 0 10]]
0.9795918367346939
1.0
0.9090909090909091


In [23]:
from sklearn.svm import LinearSVC
svm_classifier = LinearSVC(max_iter=50000)
svm_classifier.fit(X_train, y_train)

svm_y_predict = svm_classifier.predict(X_test)
svm_y_predict

from sklearn.metrics import confusion_matrix,accuracy_score,recall_score, precision_score
cm = confusion_matrix(y_test, svm_y_predict)
ac = accuracy_score(y_test,svm_y_predict)
rs = recall_score(y_test,svm_y_predict)
ps = precision_score(y_test,svm_y_predict)

print(cm)
print(ac)
print(rs)
print(ps)

[[39  0]
 [ 0 10]]
1.0
1.0
1.0


In [24]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train, y_train)

dt_y_predict = dt_classifier.predict(X_test)
dt_y_predict

from sklearn.metrics import confusion_matrix,accuracy_score,recall_score, precision_score
cm = confusion_matrix(y_test, dt_y_predict)
ac = accuracy_score(y_test,dt_y_predict)
rs = recall_score(y_test,dt_y_predict)
ps = precision_score(y_test,dt_y_predict)

print(cm)
print(ac)
print(rs)
print(ps)

[[39  0]
 [ 0 10]]
1.0
1.0
1.0


In [25]:
from sklearn.ensemble.voting import VotingClassifier
vc_classifier = VotingClassifier(
    estimators=[('nb', nb_classifier), ('svm', svm_classifier), ('dt', dt_classifier)],
    voting='hard'
)
vc_classifier.fit(X_train, y_train)

vc_y_predict = vc_classifier.predict(X_test)
vc_y_predict

from sklearn.metrics import confusion_matrix,accuracy_score,recall_score, precision_score
cm = confusion_matrix(y_test, vc_y_predict)
ac = accuracy_score(y_test,vc_y_predict)
rs = recall_score(y_test,vc_y_predict)
ps = precision_score(y_test,vc_y_predict)

print(cm)
print(ac)
print(rs)
print(ps)

[[39  0]
 [ 0 10]]
1.0
1.0
1.0
C:\Users\Mahesh\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.ensemble.voting module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)


In [26]:
from xgboost import XGBClassifier
xgb_classifier = XGBClassifier()
xgb_classifier.fit(X_train, y_train)

xgb_y_predict = xgb_classifier.predict(X_test)
xgb_y_predict

from sklearn.metrics import confusion_matrix,accuracy_score,recall_score, precision_score
cm = confusion_matrix(y_test, xgb_y_predict)
ac = accuracy_score(y_test,xgb_y_predict)
rs = recall_score(y_test,xgb_y_predict)
ps = precision_score(y_test,xgb_y_predict)

print("Confusion Matrix : \n", cm)
print('Accuracy :\n',ac)
print('Recall : \n', rs)
print('Precesion : \n', ps)

[01:14:26] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Confusion Matrix : 
 [[38  1]
 [ 0 10]]
Accuracy :
 0.9795918367346939
Recall : 
 1.0
Precesion : 
 0.9090909090909091
C:\Users\Mahesh\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


k-fold validation

In [30]:
from sklearn.model_selection import cross_val_score

In [31]:
score = cross_val_score(vc_classifier, X, y, cv=10)#, scoring='recall')
score

C:\Users\Mahesh\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\Mahesh\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\Mahesh\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\Mahesh\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\Mahesh\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of itera

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
score.mean()

1.0

In [33]:
cross_val_score(svm_classifier, X, y, cv=10)

C:\Users\Mahesh\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\Mahesh\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\Mahesh\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\Mahesh\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\Mahesh\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of itera

array([1.    , 1.    , 1.    , 1.    , 1.    , 1.    , 1.    , 1.    ,
       1.    , 0.9375])

In [36]:
score = cross_val_score(xgb_classifier, X, y, cv=10, error_score='raise')#, scoring='recall')
score.mean()

C:\Users\Mahesh\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
[01:43:24] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[01:43:24] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[01:43:24] WARNING: ..\src\learner.cc:1061

0.9625

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
cross_val_score(xgb_classifier, X, y, cv=10)

C:\Users\Mahesh\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
[01:16:48] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[01:16:48] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[01:16:48] WARNING: ..\src\learner.cc:1061

array([1.    , 1.    , 0.9375, 0.9375, 1.    , 1.    , 0.9375, 0.9375,
       1.    , 0.875 ])

In [36]:
X

Age at Histological Diagnosis  Weight (lbs)  Days between CT and surgery  \
0                               34        -999.0                            9   
1                               33        -999.0                            3   
2                               69        -999.0                           28   
3                               80        -999.0                           47   
4                               76        -999.0                            2   
..                             ...           ...                          ...   
206                             75         184.0                           14   
207                             61         231.5                           72   
208                             52        -999.0                            8   
209                             67         158.0                           65   
210                             68         229.0                           51   

     Quit Smoking  Gender_Female  Gender_Male  Ethnicity_African-American  \
0            True              0            1                           0   
1            True              1            0                           0   
2            True              1            0                           0   
3            True              1            0                           0   
4           False              0            1                           0   
..            ...            ...          ...                         ...   
206         False              0            1                           0   
207         False              0            1                           0   
208          True              1            0                           0   
209         False              0            1                           0   
210          True              0            1                           0   

     Ethnicity_Asian  Ethnicity_Caucasian  Ethnicity_Hispanic/Latino  ...  \
0                  0                    0                          0  ...   
1                  0                    0                          0  ...   
2                  0                    0                          0  ...   
3                  0                    0                          0  ...   
4                  0                    0                          0  ...   
..               ...                  ...                        ...  ...   
206                0                    1                          0  ...   
207                0                    1                          0  ...   
208                0                    1                          0  ...   
209                1                    0                          0  ...   
210                0                    1                          0  ...   

     ALK translocation status_Wildtype  Adjuvant Treatment_No  \
0                                    1                      1   
1                                    0                      1   
2                                    1                      1   
3                                    1                      1   
4                                    1                      1   
..                                 ...                    ...   
206                                  0                      1   
207                                  0                      0   
208                                  1                      1   
209                                  1                      1   
210                                  0                      0   

     Adjuvant Treatment_Yes  Chemotherapy_No  Chemotherapy_Yes  Radiation_No  \
0                         0                1                 0             1   
1                         0                1                 0             1   
2                         0                1                 0             1   
3                         0                1                 0             1   
4